version: '3.8'

services:
  whisper-api:
    # image: whisper-api:latest
    build:
      context: .
      dockerfile: dockerfile
      target: whisper-api
    ports:
      - "5001:5001"

    # If you dont have GPU comment this section
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - MODEL=large-v3
      - LANGUAGE=pl
    volumes:
      - ./models:/root/.cache/whisper
      - ./uploads:/app/uploads
    restart: unless-stopped
